CREATE TABLE
IF NOT EXISTS "index" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ON CONFLICT ROLLBACK COLLATE BINARY,
	"fid" TEXT NOT NULL ON CONFLICT ROLLBACK COLLATE NOCASE,
	"hash" TEXT,
	"filename" TEXT,
	"password" TEXT,
	"creat_date" DATE
);

CREATE TABLE
IF NOT EXISTS "users" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ON CONFLICT ROLLBACK COLLATE BINARY,
	"username" TEXT not null,
	"pw_hash" TEXT not null,
	"pms" TEXT not null
);
